# Generated by Django 4.2.2 on 2023-06-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(unique=True, verbose_name="Название gym'a"),
        ),
    ]
