# Generated by Django 4.2.2 on 2023-06-13 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='publication_start_date_time_stamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало публикации (дата)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='publication_stop_date_time_stamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец публикации (дата)'),
        ),
        migrations.AlterField(
            model_name='tagbinder',
            name='bind_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='tagbinder',
            name='create_date_time_stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки'),
        ),
        migrations.AlterField(
            model_name='tagbinder',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags_management.tag', verbose_name='Тег'),
        ),
    ]
